config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'
  resources :journal_entries
  resources :event_logs
  resources :user_logs
  resources :users
  resources :accounts

  scope '', controller: 'sessions' do
    post 'login/', action: 'login'
    get 'welcome/', action: 'welcome'
    get 'homepage/', action: 'homepage'
    get 'user_management/', action: 'user_management'
    get 'trial_balance/', action: 'trial_balance'
    get 'retained_earnings/', action: 'retained_earnings'
    get 'income_statement/', action: 'income_statement'
    get 'balance_sheet/', action: 'balance_sheet'

    get 'send_trial_balance/', action: 'send_trial_balance'
    get 'send_income_statement/', action: 'send_income_statement'
    get 'send_retained_earnings/', action: 'send_retained_earnings'
    get 'send_balance_sheet/', action: 'send_balance_sheet'

    get 'sign_up/', action: 'sign_up'
    post 'process_new_sign_up/', action: 'process_new_sign_up'
    get 'profile/', action: 'profile'
    get 'expired_passwords/', action: 'expired_passwords'
    get 'send_message/', action: 'send_message'
    get 'logout/', action: 'destroy'
    delete 'logout/', action: 'destroy'
    get 'journal/', action: 'journal'
    get '/help_index', action: 'help_index'
    get '/sign_in_help', action: 'sign_in_help'
    get '/user_management_help', action: 'user_management_help'
    get '/event_logs_help', action: 'event_logs_help'
    get '/error', action: 'error'
  end

  get 'user/destroy/:id', to: 'users#destroy'
  get 'user/edit/:id', to: 'users#edit'
  post 'user/edit/:id', to: 'users#edit'
  get 'user/update/:id', to: 'users#update'
  post 'user/update', to: 'users#update'
  get 'user/create', to: 'users#create'
  post 'user/create', to: 'users#create'
  get 'administrator/email', to: 'users#administrator_email'
  post 'administrator/email', to: 'users#administrator_email'
  post '/approve', to: 'journal_entries#approve'
  post '/decline', to: 'journal_entries#decline'
  post '/approve_all', to: 'journal_entries#approve_all'
  post '/decline_all', to: 'journal_entries#decline_all'
  get '/generate_closing_entry', to: 'journal_entries#generate_closing_entry'
  get 'ledger/:account_id', to: 'ledger_entries#show'
  get '/journal_entry/:id', to: 'journal_entries#show'
  get '/reload_page', to: 'journal_entries#reload_page'

  scope 'password/', controller: 'password' do 
    get 'reset/', action: 'reset'
    post 'reset/', action: 'reset'
    get 'forgot/', action: 'forgot'
    post 'forgot/', action: 'forgot'
  end

end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
    serialize :debit_account, Array
    serialize :credit_account, Array
    serialize :debit_total, Array
    serialize :credit_total, Array

    has_many_attached :source_document
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :set_journal_entry, only: %i[ show edit update destroy invalid_num_error ]
  rescue_from ActionView::Helpers::NumberHelper::InvalidNumberError, :with => :invalid_num_error

  rescue_from Pundit::NotAuthorizedError do 
    redirect_to error_path
  end

  # GET /journal_entries or /journal_entries.json
  def index
    authorize current_user, :user_not_admin?
    @journal_entries = JournalEntry.all
  end

  # GET /journal_entries/new
  def new
    authorize current_user, :user_not_admin?
    @sorted_active_accounts = Account.where(active: true).order(:account_number)
    @journal_entry = JournalEntry.new
  end

  # POST /journal_entries or /journal_entries.json
  def create
    authorize current_user, :user_not_admin?
    debit_account_ids = journal_entry_params[:debit_account].map(&:to_i)
    credit_account_ids = journal_entry_params[:credit_account].map(&:to_i)

    debit_amounts = journal_entry_params[:debit_total]
    credit_amounts = journal_entry_params[:credit_total]

    @journal_entry = JournalEntry.new(  user_id: current_user.id,
                                        debit_account: debit_account_ids,
                                        credit_account: credit_account_ids,
                                        debit_total: debit_amounts,
                                        credit_total: credit_amounts,
                                        entry_type: journal_entry_params[:entry_type],  
                                        status: "Pending",
                                        description: params[:journal_entry][:description]
                                      )
                                      
    @journal_entry.source_document.attach(params[:journal_entry][:source_document])

    error_list = valid?(debit_account_ids, credit_account_ids, debit_amounts, credit_amounts)
    error_list = balanced?(debit_amounts, credit_amounts) if !balanced?(debit_amounts, credit_amounts).nil?

    if error_list.nil?
      @journal_entry.date_added = params[:date].to_date
      
      if @journal_entry.save
        redirect_to journal_entries_path, warning: "Journal entry pending"
        User.where(userType: 2).pluck(:email).each do |email|
          ResetMailer.with(user_email: email).pending_journal_entry.deliver_now
        end
      else
        flash.now[:danger] = "#{@account.errors.first.full_message}"
        render new_journal_entry_path
      end
    else
      @journal_entry.debit_total = [debit_amounts.first]
      @journal_entry.credit_total = [credit_amounts.first]

      flash.now[:danger] = "#{error_list}"
      render new_journal_entry_path
    end
  end

  def approve
    authorize current_user, :user_manager?
    approve_entry(params[:entry].to_i)
    redirect_to journal_entries_path, success: ErrorMessage.find_by(error_name: "Journal_approved").body
  end

  def decline
    authorize current_user, :user_manager?
    decline_entry(params[:entry].to_i, params[:reason])
    redirect_to journal_entries_path, danger: ErrorMessage.find_by(error_name: "Journal_declined").body
  end

  def approve_all
    authorize current_user, :user_manager?
    @pending_entries = JournalEntry.where(status: "Pending")
    @pending_entries.each do |e|
      approve_entry(e.id)
    end
    redirect_to journal_entries_path, success: ErrorMessage.find_by(error_name: "Journal_all_approved").body
  end

  def decline_all
    authorize current_user, :user_manager?
    @pending_entries = JournalEntry.where(status: "Pending")
    @pending_entries.each do |e|
      decline_entry(e.id, "Manager has declined all entries")
    end
    redirect_to journal_entries_path, danger: ErrorMessage.find_by(error_name: "Journal_all_declined").body
  end

  def generate_closing_entry
    @service_revenue = Account.find_by(name: "Service Revenue")
    @expense_accounts = Account.where('balance > ?', 0).where(category: "Expense")
    @expense_accounts += Account.where(name: "Retained Earnings")
    @debit = @expense_accounts.pluck(:balance)
    @debit.pop
    
    @closing_journal_entry = JournalEntry.new(  user_id: current_user.id,
                                        debit_account:  [@service_revenue.id],
                                        credit_account: @expense_accounts.pluck(:id),
                                        debit_total:    [-@service_revenue.balance],
                                        credit_total:   @debit << Account.retained_earnings_value(),
                                        entry_type: "Closing",
                                        status: "Pending",
                                        description: "Closing entry created by #{current_user.username}",
                                        date_added: Time.now.to_date
                                      )

    if @closing_journal_entry.save
      redirect_to journal_entries_path, success: ErrorMessage.find_by(error_name: "journal_created_closing_entry").body
    else
      flash.now[:danger] = ErrorMessage.find_by(error_name: "journal_closing_entry_failed").body
      render new_journal_entry_path
    end
  end

  def show
    @journal_entry = JournalEntry.find_by(id: params[:id])
  end

  def reload_page
    redirect_to journal_entries_path
  end 

  private

    def approve_entry(id)
      @entry = JournalEntry.find(id)
      @entry.status = "Approved"
      @entry.save
      LedgerEntry.create_new_entry(@entry)
    end

    def decline_entry(id, reason)
      @entry = JournalEntry.find(id)
      @entry.status = "Declined"
      @entry.description += "\n (#{current_user.username} has declined this entry because: '#{reason}')"
      @entry.save
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_journal_entry
      @journal_entry = JournalEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_entry_params
      params.fetch(:journal_entry, {})
    end

    def valid?(debit_accounts, credit_accounts, debit, credit)
      # Checks if debit accounts are all dif
      if debit_accounts.uniq.length == debit_accounts.length
        # Checks if credit accounts are all dif
        if credit_accounts.uniq.length == credit_accounts.length
          # Checks if debit and credit accounts have same account
          if (debit_accounts - credit_accounts).count == debit_accounts.count

            # Check if debit has only 2 decimals and is not negative
            debit.each do |num|
              if num.to_f > 0
                ActionController::Base.helpers.number_to_currency(num, precision: 2, raise: true)
              else
                return "Debit amount can not be 0"
              end
            end

            # Check if credit has only 2 decimals and converts it to currency
            credit.each do |num|
              if num.to_f > 0
                ActionController::Base.helpers.number_to_currency(num, precision: 2, raise: true)
              else
                return "Credit amount can not be 0"
              end
            end

            return nil
          else
            return "You can not debit and credit from the same account"
          end
        else
          return "You can not credit from the same account twice"
        end
      else
        return "You can not debit from the same account twice"
      end
    end

    def balanced?(debit, credit)
      debit_sum = 0
      debit.each do |num|
        debit_sum += ActionController::Base.helpers.number_with_precision(num, precision: 2).to_f
      end  

      credit_sum = 0
      credit.each do |num|
        credit_sum += ActionController::Base.helpers.number_with_precision(num, precision: 2).to_f
      end 

      if debit_sum == credit_sum
        return nil
      else
        return "Total Debits and Credits are not balanced: (Debit = $#{debit_sum}, Credit = $#{credit_sum})"
      end
    end
    
    def invalid_num_error
      flash.now[:danger] = "Debit/Credit value is not a correct number"
      render new_journal_entry_path
    end
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/views/journal_entries/_form.html.erb
<%= form_with(model: journal_entry) do |form| %>
  <% if journal_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal_entry.errors.count, "error") %> prohibited this journal_entry from being saved:</h2>

      <ul>
        <% journal_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/journal_entries/index.html.erb
<%= render partial: "shared/navigation_bar"%>
<%= render 'flash_messages' %>
<p id="notice"><%= notice %></p>
<h1 class="text-center">Journal Entries</h1>
<br>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-lg-2">
      <div class="btn-group">
        <%= button_to "New Entry", new_journal_entry_path, method: :get, class: "btn btn-primary", 'data-toggle': 'tooltip', 'data-placement':'top', title: 'Create a new journal entry' %><br>
        <% if current_user.userType == 2 %> 
          <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu">
            <%= button_to "Create Closing Entry", generate_closing_entry_path, method: :get, class: "dropdown-item" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col col-lg-2">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">$</span>
        </div>
        <%= text_field_tag :min, "", placeholder: "Min", class: "form-control", id: "min"  %>
      </div>
    </div>
    <div class="col col-lg-2">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">$</span>
        </div>
        <%= text_field_tag :max, "", placeholder: "Max", class: "form-control", id: "max" %>
      </div>
    </div>

    <div class="col col-lg-2">
      <div class="input-group mb-3">
        <%= text_field_tag :mind, "", placeholder: "Start Date", class: "form-control", id: "mindate", name: "mindate"  %>
      </div>
    </div>
    <div class="col col-lg-2">
      <div class="input-group mb-3">
        <%= text_field_tag :maxd, "", placeholder: "End Date", class: "form-control", id: "maxdate", name: "maxdate" %>
      </div>
    </div>

    <div class="col col-lg-2">
			<div class="dropdown">
				<button class="btn btn-outline-secondary btn-block dropdown-toggle" type="button" id="DropDownStatus" data-toggle="dropdown">
					Filter Status
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					 <button class="dropdown-item" type = "button" id = "statusAll" disabled>All</button>
           <button class="dropdown-item" type = "button" id = "statusPending">Pending</button>
           <button class="dropdown-item" type = "button" id = "statusApproved">Approved</button>
           <button class="dropdown-item" type = "button" id = "statusDeclined">Declined</button>
				</div>
			</div>
		</div>
      <%= link_to "Clear Filters", reload_page_path %>
  </div>

  <table class="table" id="table-layout">
    <thead>
      <tr>
        <th scope="col" class="text-center">ID</th>
        <th scope="col" class="text-center">Date Added</th>
        <th scope="col" class="text-center">Entry Type</th>
        <th scope="col">User</th>
        <th scope="col">Accounts</th>
        <th scope="col" class="text-right">Debit</th>
        <th scope="col" class="text-right">Credit</th>
        <th scope="col" class="text-center">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @journal_entries.each do |journal_entry| %>
      <tr>
        <td class="text-center"><%= journal_entry.id %>
        <td class="text-center"><%= journal_entry.date_added %>
        <% if journal_entry.status == "Pending" && current_user.userType == 2 %>
          <%= button_to "Approve", approve_path(entry: journal_entry), method: :post, class: "btn btn-success btn-sm btn-block", 'data-toggle': 'tooltip', 'data-placement':'top', title: 'Approve this transaction' %>
          <button type="button" class="btn btn-danger btn-sm btn-block" data-toggle="modal" data-target="#exampleModal" title="Decline this transaction">Decline</button>
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Please add why the entry is being declined:</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <%= form_tag decline_path(entry: journal_entry), :method => :post do %>
                  <div class="container">
                    <br>
                    <%= text_area_tag :reason, nil, required: true, class: 'col-md-12 form-control', rows: '7'%>
                    <br>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <%= submit_tag 'Confirm', :class => 'btn btn-primary' %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        </td>
        <td class="text-center"><%= journal_entry.entry_type %></td>
        <td><%= User.find_by(id: journal_entry.user_id).username %></td>
        <td>
          <% journal_entry.debit_account.each do |a|%>
            <%= link_to "#{Account.find_by(id: a).account_number} - #{Account.find_by(id: a).name.truncate(20)}", "/ledger/#{a}"%><br>
          <%end%>

          <% journal_entry.credit_account.each do |a|%>
            <div style="text-indent: 40px">
              <%= link_to "#{Account.find_by(id: a).account_number} - #{Account.find_by(id: a).name.truncate(20)}", "/ledger/#{a}"%>
            </div>
          <%end%>          
        </td>
        <td class="text-right">
          <% journal_entry.debit_total.each do |num|%>
            <%= number_to_currency(num, precision: 2) %>
            <br>
          <%end%>
        </td>
        <td class="text-right">
          <% journal_entry.debit_total.each do |num|%>
            <br>
          <%end%>
          <% journal_entry.credit_total.each do |num|%>
            <%= number_to_currency(num, precision: 2) %>
            <br>
          <%end%>
        </td>
        <td class="text-center">
          <% if journal_entry.status == "Approved" %>
            <a href= <%= journal_entry_path(journal_entry.id) %> > 
              <span class="badge badge-pill badge-success"> <%= journal_entry.status %> </span> 
            </a>

          <% elsif journal_entry.status == "Declined"%>
            <a href= <%= journal_entry_path(journal_entry.id) %> > 
              <span class="badge badge-pill badge-danger"> <%= journal_entry.status %> </span> 
            </a>
          <% else %>
            <a href= <%= journal_entry_path(journal_entry.id) %> > 
              <span class="badge badge-pill badge-warning"> <%= journal_entry.status %> </span><br>
            </a>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% if JournalEntry.where(status: "Pending").count > 0 && current_user.userType == 2 && Rails.env != "production"%>
    <%= button_to "Approve all", approve_all_path, method: :post, class: "btn btn-light btn-block", style: "color:white;" %> <!-- for bug testing only  -->
    <%= button_to "Decline all", decline_all_path, method: :post, class: "btn btn-light btn-block", style: "color:white;" %>  <!-- for bug testing only  -->
  <% end %>
</div>

<script>
  var minDate, maxDate;
 
  $.fn.dataTable.ext.search.push(
      function( settings, data, dataIndex ) {
          var min = minDate.val();
          var max = maxDate.val();
          var date = new Date( data[1] );
  
          if (
              ( min === null && max === null ) ||
              ( min === null && date <= max ) ||
              ( min <= date   && max === null ) ||
              ( min <= date   && date <= max )
          ) {
              return true;
          }
          return false;
      }
  );

  $.fn.dataTable.ext.search.push(
    function amount( settings, data, dataIndex ) {
        var min = parseInt( $('#min').val(), 10 );
        var max = parseInt( $('#max').val(), 10 );
        var balance = parseFloat(data[5,6].replace('$','').replace(/,|_/g, '')).toFixed(2) || 0;
        
        if ( ( isNaN( min ) && isNaN( max ) ) ||
             ( isNaN( min ) && balance <= max ) ||
             ( min <= balance && isNaN( max ) ) ||
             ( min <= balance && balance <= max ) )
        {
            return true;
        }
        return false;
    }
  );

  $.fn.dataTable.ext.search.push(
    function status( settings, data, dataIndex ) {
      var status = data[7];
      if (document.getElementById("statusAll").disabled)
      {
        return true;
      }
      if (document.getElementById("statusPending").disabled && status.includes("Pending"))
      {
        return true;
      }
      if (document.getElementById("statusApproved").disabled && status.includes("Approved"))
      {
        return true;
      }
      if (document.getElementById("statusDeclined").disabled && status.includes("Declined"))
      {
        return true;
      }
      return false;
    }
  );
  
  $(document).ready(function() {
    minDate = new DateTime($('#mindate'), {
          format: 'MMMM Do YYYY'
      });
      maxDate = new DateTime($('#maxdate'), {
          format: 'MMMM Do YYYY'
      });
  
      //Sorts table by date
      var table = $('#table-layout').DataTable( {
                    "columnDefs": [
                      {
                        "targets": [ 0 ],
                        "visible": false,
                      }
                    ],
                    "order": [[ 0, "desc" ]]
                  } );

      
      $('#mindate, #maxdate').on('change', function () {
          table.draw();
      });

      $('#min, #max').keyup( function() {
        table.draw();
      } );

      $('#statusAll').click(function() {
        document.getElementById("statusAll").disabled = false;
        document.getElementById("statusPending").disabled = false;
        document.getElementById("statusApproved").disabled = false;
        document.getElementById("statusDeclined").disabled = false;
  
        document.getElementById("statusAll").disabled = true;
        table.draw();
      } );
      $('#statusPending').click(function() {
        document.getElementById("statusAll").disabled = false;
        document.getElementById("statusPending").disabled = false;
        document.getElementById("statusApproved").disabled = false;
        document.getElementById("statusDeclined").disabled = false;
  
        document.getElementById("statusPending").disabled = true;
        table.draw();
      } );
      $('#statusApproved').click(function() {
        document.getElementById("statusAll").disabled = false;
        document.getElementById("statusPending").disabled = false;
        document.getElementById("statusApproved").disabled = false;
        document.getElementById("statusDeclined").disabled = false;
  
        document.getElementById("statusApproved").disabled = true;
        table.draw();
      } );
      $('#statusDeclined').click(function() {
        document.getElementById("statusAll").disabled = false;
        document.getElementById("statusPending").disabled = false;
        document.getElementById("statusApproved").disabled = false;
        document.getElementById("statusDeclined").disabled = false;
        
        document.getElementById("statusDeclined").disabled = true;
        table.draw();
      } );
  });
</script>

app/views/journal_entries/new.html.erb
<%= render partial: "shared/navigation_bar"%>
<%= render 'flash_messages' %><br>
<div class="container">  
  <div class="row">
    <div class="col"></div>
      <div class="col-8 ">
        <h1 class="text-center">New Journal Entry</h1>
        <%= form_with(model: @journal_entry) do |f| %>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.label "Entry Type:" %><br>
              <%= f.select :entry_type, [["Regular", "Regular"], ["Adjusting", "Adjusting"], ["Reversing", "Reversing"]], {selected: nil}, {class: "form-control"} %>
            </div>
            <div class="form-group col-md-6">
              <%= f.label "Entry Date:" %>
              <%= text_field_tag :date, "#{Date.current}", required: true, class: "form-control", id: "entry_date" %>
            </div>
          </div>
        
          <div class="form-row">
            <div class="form-group col">
              <%= f.label "Description:" %>
              <%= f.text_area :description, class: 'form-control'%>
            </div>
          </div>

          <table class="table table-borderless" id="main_entry_table">
            <thead>
              <tr>
                <th scope="col">Debit Account:</th>
                <th scope="col">Debit:</th>
                <th scope="col">Credit:</th>
                <th></th>
              </tr>
            </thead>  
            <tbody id="debit_entry_table"
              <tr>
                <td class="debit_account_selector">
                  <%= f.select(:debit_account, Account.where(active: true).order(:account_number).collect {|p| [ p.name, p.id ] }, {}, {class: 'form-control', name: 'journal_entry[debit_account][]', required: true}) %>
                </td>
                <td>
                  <div class="debit_field">
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                      </div>
                        <%= f.text_field :debit_total, class: 'form-control', id: 'numbersOnlyDebit', value: nil, name: "journal_entry[debit_total][]", required: true %>
                    </div>  
                  </div>
                </td>
                <td></td>
                <td>
                  <a href="javascript:void(0);" class="add_debit">
                    <%= image_tag('icons/add.png', width:'20px') %>
                  </a>
                </td>
              </tr>
            </tbody>

            <tbody id="credit_entry_table"
              <tr>
                <th scope="col">Credit Account:</th>
              </tr>
              <tr>
                <td class="credit_account_selector">
                  <%= f.select(:credit_account, Account.where(active: true).order(:account_number).collect {|p| [ p.name, p.id ] }, {}, {class: 'form-control', name: 'journal_entry[credit_account][]', required: true}) %>
                </td>
                <td></td>
                <td>
                  <div class="credit_field">
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                      </div>
                        <%= f.text_field :credit_total, class: 'form-control', id: 'numbersOnlyCredit', value: nil, name: "journal_entry[credit_total][]", required: true %>
                    </div>
                  </div>    
                </td>
                <td>
                  <a href="javascript:void(0);" class="add_credit">
                    <%= image_tag('icons/add.png', width:'20px') %>
                  </a>
                </td>
              </tr>
            </tbody>
          </table>

            <%= f.file_field :source_document, required: false, multiple: true %><br><br>
          <div class="actions">
            <div class="form-row">
              <div class="col-6">
                <%= f.submit class: "btn btn-primary btn-block", 'data-toggle': 'tooltip', 'data-placement':'top', title: 'Submit this journal entry'%>
              </div>
              <div class="col-6">
                <%= link_to "Cancel", journal_entries_path, class: "btn btn-secondary btn-block", 'data-toggle': 'tooltip', 'data-placement':'top', title: 'Cancel this journal entry' %>
              </div>
            </div>
            <div class="form-row">
              <div class="col text-center" style="padding-top:10px;">
                <%= link_to "Clear/Reset", new_journal_entry_path %>
              </div>
            </div>
          </div><br><br>
        <%end%>
      </div>
    <div class="col"></div>
  </div>
</div>


<style>
  .table-borderless > tbody > tr > td,
  .table-borderless > tbody > tr > th,
  .table-borderless > tfoot > tr > td,
  .table-borderless > tfoot > tr > th,
  .table-borderless > thead > tr > td,
  .table-borderless > thead > tr > th {
      border: none;
  }
</style>


<script>
  $(document).ready(function(){
    $(".add_debit").click(function(){
      var account_select = $(".debit_account_selector").html();
      var text_box = $(".debit_field").html();
      var remove_row_button = "<a href='javascript:void(0);' class='remove_debit'><img width='20px' src='/assets/icons/minus-6430b402fa06620735037bae2a8e7ff032304ece1ff16995c5408d3830bd4eb3.png'></a>"
      $("#debit_entry_table").append('<tr><td>' + account_select + '</td><td>' + text_box + '</td><td></td><td>' + remove_row_button + '</td></tr>');
    });

    $("#debit_entry_table").on('click','.remove_debit',function(){
        $(this).parent().parent().remove();
    });

    $(".add_credit").click(function(){
      var account_select = $(".credit_account_selector").html();
      var text_box = $(".credit_field").html();
      var remove_row_button = "<a href='javascript:void(0);' class='remove_credit'><img width='20px' src='/assets/icons/minus-6430b402fa06620735037bae2a8e7ff032304ece1ff16995c5408d3830bd4eb3.png'></a>"
      $("#credit_entry_table").append('<tr><td>' + account_select + '</td><td></td><td>' + text_box + '</td><td>' + remove_row_button + '</td></tr>');
    });

    $("#credit_entry_table").on('click','.remove_credit',function(){
        $(this).parent().parent().remove();
    });

    $("#numbersOnlyDebit, #numbersOnlyCredit").keyup(function () { 
      this.value = this.value.replace(/[^0-9\.]/g,'');
      this.value = this.value.match(/^\d+\.?\d{0,2}/);
    });
  });

  new DateTime($('#entry_date'), {
      buttons: {
          today: true,
      }
});
</script>