config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'
  resources :journal_entries
  resources :event_logs
  resources :user_logs
  resources :users
  resources :accounts

  scope '', controller: 'sessions' do
    post 'login/', action: 'login'
    get 'welcome/', action: 'welcome'
    get 'homepage/', action: 'homepage'
    get 'user_management/', action: 'user_management'
    get 'trial_balance/', action: 'trial_balance'
    get 'retained_earnings/', action: 'retained_earnings'
    get 'income_statement/', action: 'income_statement'
    get 'balance_sheet/', action: 'balance_sheet'

    get 'send_trial_balance/', action: 'send_trial_balance'
    get 'send_income_statement/', action: 'send_income_statement'
    get 'send_retained_earnings/', action: 'send_retained_earnings'
    get 'send_balance_sheet/', action: 'send_balance_sheet'

    get 'sign_up/', action: 'sign_up'
    post 'process_new_sign_up/', action: 'process_new_sign_up'
    get 'profile/', action: 'profile'
    get 'expired_passwords/', action: 'expired_passwords'
    get 'send_message/', action: 'send_message'
    get 'logout/', action: 'destroy'
    delete 'logout/', action: 'destroy'
    get 'journal/', action: 'journal'
    get '/help_index', action: 'help_index'
    get '/sign_in_help', action: 'sign_in_help'
    get '/user_management_help', action: 'user_management_help'
    get '/event_logs_help', action: 'event_logs_help'
    get '/error', action: 'error'
  end

  get 'user/destroy/:id', to: 'users#destroy'
  get 'user/edit/:id', to: 'users#edit'
  post 'user/edit/:id', to: 'users#edit'
  get 'user/update/:id', to: 'users#update'
  post 'user/update', to: 'users#update'
  get 'user/create', to: 'users#create'
  post 'user/create', to: 'users#create'
  get 'administrator/email', to: 'users#administrator_email'
  post 'administrator/email', to: 'users#administrator_email'
  post '/approve', to: 'journal_entries#approve'
  post '/decline', to: 'journal_entries#decline'
  post '/approve_all', to: 'journal_entries#approve_all'
  post '/decline_all', to: 'journal_entries#decline_all'
  get '/generate_closing_entry', to: 'journal_entries#generate_closing_entry'
  get 'ledger/:account_id', to: 'ledger_entries#show'
  get '/journal_entry/:id', to: 'journal_entries#show'
  get '/reload_page', to: 'journal_entries#reload_page'

  scope 'password/', controller: 'password' do 
    get 'reset/', action: 'reset'
    post 'reset/', action: 'reset'
    get 'forgot/', action: 'forgot'
    post 'forgot/', action: 'forgot'
  end

end

app/models/event_log.rb
class EventLog < ApplicationRecord
end

app/controllers/event_logs_controller.rb
class EventLogsController < ApplicationController
  before_action :set_event_log, only: %i[ show edit update destroy ]

  # GET /event_logs or /event_logs.json
  def index
    # These events still are in json and need to be converted for the view
    @raw_event_logs = EventLog.all.reverse()
    @event_logs = []
    @raw_event_logs.each do |event|
      if event.event_type == "Modified"
        before_model = convert_json_to_model(event.account_before)
        after_model = convert_json_to_model(event.account_after)
        @event_logs << [event, before_model, after_model]

      elsif event.event_type == "Added"
        before_model = nil
        after_model = convert_json_to_model(event.account_after)
        @event_logs << [event, before_model, after_model]

      elsif event.event_type == "Deactivated"
        before_model = convert_json_to_model(event.account_before)
        after_model = convert_json_to_model(event.account_after)
        @event_logs << [event, before_model, after_model]
      end
    end
    @approved_journal_entries = JournalEntry.where(status: "Approved")
    @user_logs = UserEventLog.user_log_models()
  end

  # GET /event_logs/1 or /event_logs/1.json
  def show
    @event_id = params[:id][/\d+/]
    if EventLog.find(@event_id).account_before.empty?
      @before = Account.new
      @after = convert_json_to_model(EventLog.find(@event_id).account_after)

    elsif EventLog.find(@event_id).account_after.empty?
      @before = convert_json_to_model(EventLog.find(@event_id).account_before)
      @after = Account.new
    else
      @before = convert_json_to_model(EventLog.find(@event_id).account_before)
      @after = convert_json_to_model(EventLog.find(@event_id).account_after)
    end
  end

  # GET /event_logs/new
  def new
    @event_log = EventLog.new
  end

  # GET /event_logs/1/edit
  def edit
  end

  # POST /event_logs or /event_logs.json
  def create
    @event_log = EventLog.new(event_log_params)
  end

  # PATCH/PUT /event_logs/1 or /event_logs/1.json
  def update
    respond_to do |format|
      if @event_log.update(event_log_params)
        format.html { redirect_to @event_log, notice: "Event log was successfully updated." }
        format.json { render :show, status: :ok, location: @event_log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_logs/1 or /event_logs/1.json
  def destroy
    @event_log.destroy
    respond_to do |format|
      format.html { redirect_to event_logs_url, notice: "Event log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_log
      @event_log = EventLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_log_params
      params.fetch(:event_log, {})
    end

    def convert_json_to_model(json)
      JSON.parse(json, object_class: Account)
    end
end

app/helpers/event_logs_helper.rb
module EventLogsHelper
end

app/views/event_logs/_form.html.erb
<%= form_with(model: event_log) do |form| %>
  <% if event_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_log.errors.count, "error") %> prohibited this event_log from being saved:</h2>

      <ul>
        <% event_log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_logs/edit.html.erb
<h1>Editing Event Log</h1>

<%= render 'form', event_log: @event_log %>

<%= link_to 'Show', @event_log %> |
<%= link_to 'Back', event_logs_path %>

app/views/event_logs/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= render partial: "shared/navigation_bar"%>
<%= render 'flash_messages' %><br>
<div class= "container">
  <h1 class="text-center">Event Logs</h1>
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-events-tab" data-toggle="pill" href="#pills-events" role="tab" aria-controls="pills-events" aria-selected="true">Account Logs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-journal-entries-tab" data-toggle="pill" href="#pills-journal-entries" role="tab" aria-controls="pills-journal-entries" aria-selected="false">Entry Logs</a>
    </li>
    <% if current_user.userType == 1 %>
      <li class="nav-item">
        <a class="nav-link" id="pills-users-tab" data-toggle="pill" href="#pills-users" role="tab" aria-controls="pills-user" aria-selected="false">User Logs</a>
      </li>
    <%end%>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-events" role="tabpanel" aria-labelledby="pills-events-tab">
      <table class="table table-hover table-sm", id="table-layout-1">
        <thead>
          <tr class="table">
            <th scope="col">#</th>
            <th scope="col">Changed By</th>
            <th scope="col">Account</th>
            <th scope="col">Action</th>
            <th scope="col">Changed</th>
            <th scope="col">Before</th>
            <th scope="col">After</th>
            <th scope="col">Date</th>
            <th scope="col"></th> 
          </tr>
        </thead>

        <tbody>
          <% @event_logs.each do |event_log| %>

            <tr>
              <th scope="row"><%= event_log.first.id.to_s %></th>
              <td><%= event_log.first.user_name.truncate(10) %></td>
              <td><%= event_log.first.account_name.truncate(15) %></td>
              <td> 
                <% if event_log.first.event_type == "Added" %>
                  <span class="badge badge-pill badge-success"> <%= event_log.first.event_type %>   </span> 
                <% elsif event_log.first.event_type == "Deactivated"%>
                  <span class="badge badge-pill badge-danger"> <%= event_log.first.event_type %>   </span> 
                <% else %>
                  <span class="badge badge-pill badge-warning"> <%= event_log.first.event_type %>   </span> 
                <%end%>
              </td>



              <td>
                <table class="table">
                  <tr><td>Account #</td></tr>
                  <tr><td>Name</td></tr>
                  <tr><td>Type</td></tr>
                  <tr><td>Balance</td></tr>
                  <tr><td>Active</td></tr>
                </table>
              </td>
              <td>

                <% if !event_log.second.nil? %>
                  <table class="table table-borderless" >
                    <tr><td><%= event_log.second.account_number unless nil %></td></tr>
                    <tr><td><%= event_log.second.name %></td></tr>
                    <tr><td><%= event_log.second.category %></td></tr>
                    <tr><td>$<%= number_with_precision(event_log.second.balance, precision: 2, delimiter: ',') %></td></tr>
                    <tr><td><%= event_log.second.active %></td></tr>
                  </table>
                <%else%>
                  <table class="table table-borderless">
                    <tr><td>None</td></tr>
                    <tr><td>None</td></tr>
                    <tr><td>None</td></tr>
                    <tr><td>None</td></tr>
                    <tr><td>None</td></tr>
                  </table>
                <%end%>

              </td>
              <td>

                <% if !event_log.third.nil? %>
                  <table class="table table-borderless">
                    <tr><td><%= event_log.third.account_number %></td></tr>
                    <tr><td><%= event_log.third.name %></td></tr>
                    <tr><td><%= event_log.third.category %></td></tr>
                    <tr><td>$<%= number_with_precision(event_log.third.balance, precision: 2, delimiter: ',') %></td></tr>
                    <tr><td><%= event_log.third.active %></td></tr>
                  </table>
                <%else%>
                  <table class="table table-borderless">
                    <tr><td>None</td></tr>
                    <tr><td>None</td></tr>
                    <tr><td>None</td></tr>
                    <tr><td>None</td></tr>
                    <tr><td>None</td></tr>
                  </table>
                <%end%>

              </td>
              <td><%= event_log.first.created_at.to_date %></td>
              <td><%= button_to 'View', event_log_path(event_log), method: :get, class: "btn btn-primary btn-sm float-right"'btn btn-primary btn-block', 'data-toggle': 'tooltip', 'data-placement':'top', title: 'View this log entry' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="tab-pane fade" id="pills-journal-entries" role="tabpanel" aria-labelledby="pills-journal-entries-tab">
      <table class="table" id="table-layout-2">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col" class="text-center">Date Added</th>
            <th scope="col" class="text-center">Entry Type</th>
            <th scope="col" class="text-center">Created by</th>
            <th scope="col">Accounts</th>
            <th scope="col" class="text-right">Debit</th>
            <th scope="col" class="text-right">Credit</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @approved_journal_entries.each do |journal_entry| %>
          <tr>
            <td><%= journal_entry.id %></td>
            <td class="text-center"><%= journal_entry.date_added %></td>
            <td class="text-center"><%= journal_entry.entry_type %></td>
            <td class="text-center"><%= User.find_by(id: journal_entry.user_id).username.truncate(10) %></td>
            <td>
              <% journal_entry.debit_account.each do |a|%>
                <%= link_to "#{Account.find_by(id: a).account_number} - #{Account.find_by(id: a).name.truncate(10)}", "/ledger/#{a}"%><br>
              <%end%>

              <% journal_entry.credit_account.each do |a|%>
                <div style="text-indent: 40px">
                  <%= link_to "#{Account.find_by(id: a).account_number} - #{Account.find_by(id: a).name.truncate(10)}", "/ledger/#{a}"%>
                </div>
              <%end%>          
            </td>
            <td class="text-right">
              <% journal_entry.debit_total.each do |num|%>
                <%= number_to_currency(num, precision: 2) %>
                <br>
              <%end%>
            </td>
            <td class="text-right">
              <% journal_entry.debit_total.each do |num|%>
                <br>
              <%end%>
              <% journal_entry.credit_total.each do |num|%>
                <%= number_to_currency(num, precision: 2) %>
                <br>
              <%end%>
            </td>
            <td><%= button_to 'View', journal_entry_path(journal_entry.id), method: :get, class: "btn btn-primary btn-sm float-right", 'data-toggle': 'tooltip', 'data-placement':'top', title: 'View this journal entry' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% if current_user.userType == 1 %>
      <div class="tab-pane fade" id="pills-users" role="tabpanel" aria-labelledby="pills-users-tab">
        <table class="table" id="table-layout-3">
          <thead>
            <tr class="table">
              <th scope="col">#</th>
              <th scope="col">Changed By</th>
              <th scope="col">Action</th>
              <th scope="col">Changed</th>
              <th scope="col">Before</th>
              <th scope="col">After</th>
              <th scope="col">Date</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @user_logs.each do |user_log| %>
              <tr>
                <th scope="row"><%= user_log.first.id.to_s %></th>
                <td><%= user_log.first.user_name.truncate(10) %></td>
                <td> 
                  <% if user_log.first.event_type == "Added" %>
                    <span class="badge badge-pill badge-success"><%= user_log.first.event_type %></span> 
                  <% elsif user_log.first.event_type == "Deactivated"%>
                    <span class="badge badge-pill badge-danger"><%= user_log.first.event_type %></span> 
                  <% else %>
                    <span class="badge badge-pill badge-warning"><%= user_log.first.event_type %></span> 
                  <%end%>
                </td>
                <td>
                  <table class="table">
                    <tr><td>Username</td></tr>
                    <tr><td>Email</td></tr>
                    <tr><td>Phone</td></tr>
                    <tr><td>Address</td></tr>
                    <tr><td>Role</td></tr>
                    <tr><td>Active</td></tr>
                  </table>
                </td>
                <td>
                  <% if !user_log.second.nil? %>
                    <table class="table table-borderless" >
                      <tr><td><%= user_log.second.username unless nil %></td></tr>
                      <tr><td><%= user_log.second.email %></td></tr>
                      <tr><td><%= user_log.second.phoneNum %></td></tr>
                      <tr><td><%= user_log.second.address.truncate(20) %></td></tr>
                      <tr><td>
                        <% if user_log.second.userType == 1 %>
                          Admin
                        <%elsif user_log.second.userType == 2 %>
                          Manager
                        <%elsif user_log.second.userType == 3 %>
                          Accountant
                        <%end%>
                      </td></tr>
                      <tr><td><%= user_log.second.active %></td></tr>
                    </table>
                  <%else%>
                    <table class="table table-borderless">
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                    </table>
                  <%end%>
                </td>
                <td>
                  <% if !user_log.third.nil? %>
                    <table class="table table-borderless">
                      <tr><td><%= user_log.third.username unless nil %></td></tr>
                      <tr><td><%= user_log.third.email %></td></tr>
                      <tr><td><%= user_log.third.phoneNum %></td></tr>
                      <tr><td><%= user_log.third.address.truncate(20) %></td></tr>
                      <tr><td>
                        <% if user_log.third.userType == 1 %>
                          Admin
                        <%elsif user_log.third.userType == 2 %>
                          Manager
                        <%elsif user_log.third.userType == 3 %>
                          Accountant
                        <%end%>
                      </td></tr>                    
                      <tr><td><%= user_log.third.active %></td></tr>
                    </table>
                  <%else%>
                    <table class="table table-borderless">
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                      <tr><td>None</td></tr>
                    </table>
                  <%end%>
                </td>
                <td><%= user_log.first.created_at.to_date %></td>   
                <td><%= button_to 'View', user_log_path(user_log), method: :get, class: "btn btn-primary btn-sm float-right"'btn btn-primary btn-block', 'data-toggle': 'tooltip', 'data-placement':'top', title: 'View this user entry' %></td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    <%end%>
  </div>
</div>


<script>
  $(document).ready(function() {
    $('#table-layout-1').dataTable(
      {
        "order": [[ 0, "desc" ]]
      }
    );
  
    $('#table-layout-2').dataTable(
      {
        "order": [[ 0, "desc" ]]
      }
    );

    $('#table-layout-3').dataTable(
      {
        "order": [[ 0, "desc" ]]
      }
    );
  });
</script>

app/views/event_logs/new.html.erb
<h1>New Event Log</h1>

<%= render 'form', event_log: @event_log %>

<%= link_to 'Back', event_logs_path %>

app/views/event_logs/show.html.erb
<%= render partial: "shared/navigation_bar"%>
<%= render 'flash_messages' %><br>
<div class="container">
      <h1 class="text-center">Account Log Details</h1><br>
  <div class="form-row">
    <div class="col">
      <p>Event ID: <%= @event_id %></p>
    </div>
    <div class="col text-center">
      <p>Event Type:
        <% if EventLog.find(@event_id).event_type == "Added" %>
          <span class="badge badge-pill badge-success"> <%= EventLog.find(@event_id).event_type %>   </span> 
        <% elsif EventLog.find(@event_id).event_type == "Deactivated"%>
          <span class="badge badge-pill badge-danger"> <%= EventLog.find(@event_id).event_type %>   </span> 
        <% else %>
          <span class="badge badge-pill badge-warning"> <%= EventLog.find(@event_id).event_type%>   </span> 
        <%end%>  
      </p>
    </div>
    <div class="col">
      <p class="text-right"><%= link_to 'Back to Event Logs', event_logs_path %></p>
    </div>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr class="table">
        <th scope="col">Fields Changed</th>
        <th scope="col">Before</th>
        <th scope="col">After</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <th scope="row">Account ID</th>
          <td><%= @before.id %></td>
          <td><%= @after.id %></td>
        </tr>
        <tr>
          <th scope="row">User ID</th>
          <td><%= @before.user_id %></td>
          <td><%= @after.user_id %></td>
        </tr>
        <tr>
          <th scope="row">Account Name</th>
          <td><%= @before.name %></td>
          <td><%= @after.name %></td>
        </tr>
        <tr>
          <th scope="row">Account #</th>
          <td><%= @before.account_number %></td>
          <td><%= @after.account_number %></td>
        </tr>
        <tr>
          <th scope="row">Normal Side</th>
          <td><%= @before.normal_side %></td>
          <td><%= @after.normal_side %></td>
        </tr>
        <tr>
          <th scope="row">Category</th>
          <td><%= @before.category %></td>
          <td><%= @after.category %></td>
        </tr>
        <tr>
          <th scope="row">Subcategory</th>
          <td><%= @before.subcategory %></td>
          <td><%= @after.subcategory %></td>
        </tr>
        <tr>
          <th scope="row">Inital Balance</th>
          <td>$ <%= @before.initial_balance %></td>
          <td>$ <%= @after.initial_balance %></td>
        </tr>
        <tr>
          <th scope="row">Balance</th>
          <td>$ <%= @before.balance %></td>
          <td>$ <%= @after.balance %></td>
        </tr>
        <tr>
          <th scope="row">Statement</th>
          <td><%= @before.statement %></td>
          <td><%= @after.statement %></td>
        </tr>
        <tr>
          <th scope="row">Description</th>
          <td><%= @before.description %></td>
          <td><%= @after.description %></td>
        </tr>
        <tr>
          <th scope="row">Comment</th>
          <td><%= @before.comment %></td>
          <td><%= @after.comment %></td>
        </tr>
        <tr>
          <th scope="row">Active</th>
          <% if @before.id.nil? %>
            <td>false</td>
            <td><%= @after.active %></td>
          <% elsif @after.id.nil? %>
            <td><%= @before.active %></td>
            <td>false</td>
          <%else%>
            <td><%= @before.active %></td>
            <td><%= @after.active %></td>
          <%end%>
        </tr>
      </tbody>
  </table>

</div>