config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'
  resources :journal_entries
  resources :event_logs
  resources :user_logs
  resources :users
  resources :accounts

  scope '', controller: 'sessions' do
    post 'login/', action: 'login'
    get 'welcome/', action: 'welcome'
    get 'homepage/', action: 'homepage'
    get 'user_management/', action: 'user_management'
    get 'trial_balance/', action: 'trial_balance'
    get 'retained_earnings/', action: 'retained_earnings'
    get 'income_statement/', action: 'income_statement'
    get 'balance_sheet/', action: 'balance_sheet'

    get 'send_trial_balance/', action: 'send_trial_balance'
    get 'send_income_statement/', action: 'send_income_statement'
    get 'send_retained_earnings/', action: 'send_retained_earnings'
    get 'send_balance_sheet/', action: 'send_balance_sheet'

    get 'sign_up/', action: 'sign_up'
    post 'process_new_sign_up/', action: 'process_new_sign_up'
    get 'profile/', action: 'profile'
    get 'expired_passwords/', action: 'expired_passwords'
    get 'send_message/', action: 'send_message'
    get 'logout/', action: 'destroy'
    delete 'logout/', action: 'destroy'
    get 'journal/', action: 'journal'
    get '/help_index', action: 'help_index'
    get '/sign_in_help', action: 'sign_in_help'
    get '/user_management_help', action: 'user_management_help'
    get '/event_logs_help', action: 'event_logs_help'
    get '/error', action: 'error'
  end

  get 'user/destroy/:id', to: 'users#destroy'
  get 'user/edit/:id', to: 'users#edit'
  post 'user/edit/:id', to: 'users#edit'
  get 'user/update/:id', to: 'users#update'
  post 'user/update', to: 'users#update'
  get 'user/create', to: 'users#create'
  post 'user/create', to: 'users#create'
  get 'administrator/email', to: 'users#administrator_email'
  post 'administrator/email', to: 'users#administrator_email'
  post '/approve', to: 'journal_entries#approve'
  post '/decline', to: 'journal_entries#decline'
  post '/approve_all', to: 'journal_entries#approve_all'
  post '/decline_all', to: 'journal_entries#decline_all'
  get '/generate_closing_entry', to: 'journal_entries#generate_closing_entry'
  get 'ledger/:account_id', to: 'ledger_entries#show'
  get '/journal_entry/:id', to: 'journal_entries#show'
  get '/reload_page', to: 'journal_entries#reload_page'

  scope 'password/', controller: 'password' do 
    get 'reset/', action: 'reset'
    post 'reset/', action: 'reset'
    get 'forgot/', action: 'forgot'
    post 'forgot/', action: 'forgot'
  end

end

app/views/shared/_alternate_navigation_bar.html.erb
<div class="mx-auto order-0">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a href="homepage"><%= image_tag("logo.png", width: '50px', :class => "mr-auto d-block")%></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
        <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
</div>

app/views/shared/_calendar.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
</head>
<body>
 
<p>Date: <input type="text" id="datepicker"></p>
 
 
</body>
</html>

app/views/shared/_calendars.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Select a Date Range</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
  <script>
  $( function() {
    var dateFormat = "mm/dd/yy",
      from = $( "#from" )
        .datepicker({
          defaultDate: "+1w",
          changeMonth: true,
        })
        .on( "change", function() {
          to.datepicker( "option", "minDate", getDate( this ) );
        }),
      to = $( "#to" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
      })
      .on( "change", function() {
        from.datepicker( "option", "maxDate", getDate( this ) );
      });
 
    function getDate( element ) {
      var date;
      try {
        date = $.datepicker.parseDate( dateFormat, element.value );
      } catch( error ) {
        date = null;
      }
 
      return date;
    }
  } );
  </script>
</head>
<body>
 
<label for="from">Start Date:</label>
<input type="text" id="from" name="from">
<label for="to">End Date:</label>
<input type="text" id="to" name="to">
 
 
</body>
</html>

app/views/shared/_navigation_bar.html.erb
<div id="topheader">
  <nav class="navbar navbar-expand-sm navbar navbar-dark bg-primary">
    <div class="container-fluid">

      <%= image_tag("logo.png", width: '60px', class: "mr-auto d-block")%>
      <%= link_to "MoneyBinder", homepage_path, class: "navbar-brand", style: "padding-left:10px" %>
    
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto nav-fill w-75" id= navSelect>
          <li class="nav-item <%= active_class(homepage_path) %>">
            <%= link_to 'Dashboard', homepage_path, class: "nav-link"%>
          </li>

          <% if current_user.userType != 1 %>
          <li class="nav-item <%= active_class(journal_entries_path) %>">
            <%= link_to 'Journalize', journal_entries_path, class: "nav-link"%>
          </li>
          <% end %>

          <li class="nav-item <%= active_class(accounts_path) %>">
            <%= link_to 'Chart of Accounts', accounts_path, class: "nav-link"%>
          </li>

          <li class="nav-item <%= active_class(event_logs_path) %>">
            <%= link_to 'Event Logs', event_logs_path, class: "nav-link"%>
          </li>
          <% if current_user.userType != 1 %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reports</a>
              <div class="dropdown-menu">
                <%= link_to 'Trial Balance',      trial_balance_path,     class: "dropdown-item"%>
                <%= link_to 'Income Statement',   income_statement_path,  class: "dropdown-item"%>
                <%= link_to 'Retained Earnings',  retained_earnings_path, class: "dropdown-item"%>
                <%= link_to 'Balance Sheet',      balance_sheet_path,     class: "dropdown-item"%>
              </div>
            </li>
          <% end %>

          <% if current_user.userType == 1 %>
            <li class="nav-item <%= active_class(user_management_path) %>">
              <%= link_to 'User Management', user_management_path, class: "nav-link"%>
            </li>
          <%end%>
          <!-- <button class="btn btn-primary bi-arrow-left hBack" type="button"></button>
          <button class="btn btn-primary bi-arrow-right hForward" type="button"></button> -->
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <p style="line-height:40%" class="text-center">
                <a class="nav-link"></a>
                <%= link_to 'Help', asset_path("documentation/User_Manual.pdf"), class: "nav-link"%>
                <%= link_to "Email", send_message_path, class: "nav-link"%>
              </p>
            </li>
            <a href="#" class="nav-link">
              <%= image_tag("profile.jpeg", width: '50px', :class => "ml-auto d-block")%>
            </a>
            <li class="nav-item">
              <p style="line-height:10%">
                <a class="nav-link"></a>
                <a class="nav-link" href="#" style="color: white;"><%= current_user.username %></a>
                <a class="nav-link" href="/logout"><font size="-1">Logout</font></a>
              </p>
            </li>
          </ul>
        </form>
      </div>
    </div>
  </nav>
</div>

<style>
  #topheader .navbar-nav li > a {
    text-transform: capitalize;
  }
  #topheader .navbar-nav li.active > a {
    color: #fff;
    text-decoration:underline
  }
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script>
$(".hBack").on("click", function(e){
    e.preventDefault();
    window.history.back();
});
$(".hForward").on("click", function(e){
    e.preventDefault();
    window.history.forward();
});
</script>