config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'
  resources :journal_entries
  resources :event_logs
  resources :user_logs
  resources :users
  resources :accounts

  scope '', controller: 'sessions' do
    post 'login/', action: 'login'
    get 'welcome/', action: 'welcome'
    get 'homepage/', action: 'homepage'
    get 'user_management/', action: 'user_management'
    get 'trial_balance/', action: 'trial_balance'
    get 'retained_earnings/', action: 'retained_earnings'
    get 'income_statement/', action: 'income_statement'
    get 'balance_sheet/', action: 'balance_sheet'

    get 'send_trial_balance/', action: 'send_trial_balance'
    get 'send_income_statement/', action: 'send_income_statement'
    get 'send_retained_earnings/', action: 'send_retained_earnings'
    get 'send_balance_sheet/', action: 'send_balance_sheet'

    get 'sign_up/', action: 'sign_up'
    post 'process_new_sign_up/', action: 'process_new_sign_up'
    get 'profile/', action: 'profile'
    get 'expired_passwords/', action: 'expired_passwords'
    get 'send_message/', action: 'send_message'
    get 'logout/', action: 'destroy'
    delete 'logout/', action: 'destroy'
    get 'journal/', action: 'journal'
    get '/help_index', action: 'help_index'
    get '/sign_in_help', action: 'sign_in_help'
    get '/user_management_help', action: 'user_management_help'
    get '/event_logs_help', action: 'event_logs_help'
    get '/error', action: 'error'
  end

  get 'user/destroy/:id', to: 'users#destroy'
  get 'user/edit/:id', to: 'users#edit'
  post 'user/edit/:id', to: 'users#edit'
  get 'user/update/:id', to: 'users#update'
  post 'user/update', to: 'users#update'
  get 'user/create', to: 'users#create'
  post 'user/create', to: 'users#create'
  get 'administrator/email', to: 'users#administrator_email'
  post 'administrator/email', to: 'users#administrator_email'
  post '/approve', to: 'journal_entries#approve'
  post '/decline', to: 'journal_entries#decline'
  post '/approve_all', to: 'journal_entries#approve_all'
  post '/decline_all', to: 'journal_entries#decline_all'
  get '/generate_closing_entry', to: 'journal_entries#generate_closing_entry'
  get 'ledger/:account_id', to: 'ledger_entries#show'
  get '/journal_entry/:id', to: 'journal_entries#show'
  get '/reload_page', to: 'journal_entries#reload_page'

  scope 'password/', controller: 'password' do 
    get 'reset/', action: 'reset'
    post 'reset/', action: 'reset'
    get 'forgot/', action: 'forgot'
    post 'forgot/', action: 'forgot'
  end

end

app/models/ledger_entry.rb
class LedgerEntry < ApplicationRecord

  def self.create_new_entry(entry)
    (0..entry.debit_account.count-1).each do |index|
      accountId = entry.debit_account[index]
      ledger_debit = entry.debit_total[index]
      post_ref = entry.id
      desc = entry.description
      
      new_ledger_entry = LedgerEntry.create( 
                          account_id: accountId, 
                          postReference: post_ref, 
                          debit: ledger_debit, 
                          description: desc,
                          created_at: entry.date_added
                        )
      new_balance = Account.update_account_balance(accountId)
      new_ledger_entry.balance = new_balance
      new_ledger_entry.save    
    end 

    (0..entry.credit_account.count-1).each do |index|
      accountId = entry.credit_account[index]
      ledger_credit = entry.credit_total[index]
      post_ref = entry.id
      desc = entry.description

      new_ledger_entry = LedgerEntry.create( 
                          account_id: accountId, 
                          postReference: post_ref, 
                          credit: ledger_credit, 
                          description: desc,
                          created_at: entry.date_added 
                        )
      new_balance = Account.update_account_balance(accountId)
      new_ledger_entry.balance = new_balance
      new_ledger_entry.save
    end 
  end
end

app/controllers/ledger_entries_controller.rb
class LedgerEntriesController < ApplicationController
  # before_action :set_ledger_entry, only: %i[ show edit update destroy ]

  # GET /ledger_entries or /ledger_entries.json
  # def index
  #   @ledger_entries = LedgerEntry.all
  # end

  # GET /ledger_entries/1 or /ledger_entries/1.json
  def show
    @account = Account.find_by(id: params[:account_id])
    @ledger_entries = LedgerEntry.where(account_id: @account.id)
  end

  # GET /ledger_entries/new
  # def new
  #   @ledger_entry = LedgerEntry.new
  # end

  # GET /ledger_entries/1/edit
  # def edit
  # end

  # POST /ledger_entries or /ledger_entries.json
  # def create
  #   @ledger_entry = LedgerEntry.new(ledger_entry_params)

  #   respond_to do |format|
  #     if @ledger_entry.save
  #       format.html { redirect_to @ledger_entry, notice: "Ledger entry was successfully created." }
  #       format.json { render :show, status: :created, location: @ledger_entry }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @ledger_entry.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /ledger_entries/1 or /ledger_entries/1.json
  # def update
  #   respond_to do |format|
  #     if @ledger_entry.update(ledger_entry_params)
  #       format.html { redirect_to @ledger_entry, notice: "Ledger entry was successfully updated." }
  #       format.json { render :show, status: :ok, location: @ledger_entry }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @ledger_entry.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /ledger_entries/1 or /ledger_entries/1.json
  # def destroy
  #   @ledger_entry.destroy
  #   respond_to do |format|
  #     format.html { redirect_to ledger_entries_url, notice: "Ledger entry was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_ledger_entry
    #   @ledger_entry = LedgerEntry.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    # def ledger_entry_params
    #   params.fetch(:ledger_entry, {})
    # end
end

app/helpers/ledger_entries_helper.rb
module LedgerEntriesHelper
end

app/views/ledger_entries/edit.html.erb
<h1>Editing Ledger Entry</h1>

<%= render 'form', ledger_entry: @ledger_entry %>

<%= link_to 'Show', @ledger_entry %> |
<%= link_to 'Back', ledger_entries_path %>

app/views/ledger_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ledger Entries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ledger_entries.each do |ledger_entry| %>
      <tr>
        <td><%= link_to 'Show', ledger_entry %></td>
        <td><%= link_to 'Edit', edit_ledger_entry_path(ledger_entry) %></td>
        <td><%= link_to 'Destroy', ledger_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ledger Entry', new_ledger_entry_path %>

app/views/ledger_entries/show.html.erb
<%= render partial: "shared/navigation_bar"%>
<%= render 'flash_messages' %>
<br>
<div class="container">
  <h1 class="text-center"><%= @account.account_number %> - <%= @account.name %></h1>

  <div class="row justify-content-md-left">
    <div class="col col-lg-2">
      <div class="input-group mb-3">
        <%= text_field_tag :mind, "", placeholder: "Start Date", class: "form-control", id: "mindate", name: "mindate"  %>
      </div>
    </div>
    <div class="col col-lg-2">
      <div class="input-group mb-3">
        <%= text_field_tag :maxd, "", placeholder: "End Date", class: "form-control", id: "maxdate", name: "maxdate" %>
      </div>
    </div>
    <div class="col text-right">
      <button class="btn btn-link bi-arrow-left hBack" type="button"> Back</button>
    </div>
  </div>

  <table class="table" id="table-layout">
    <thead>
    <tr>
        <th scope="col">Date</th>
        <th scope="col">Post-Ref</th>
        <th scope="col">Description</th>
        <th scope="col">Debit</th>
        <th scope="col">Credit</th>
        <th scope="col">Balance</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="text-right"><%= number_to_currency(@account.initial_balance, precision: 2) %></td>
      </tr>
      <% @ledger_entries.each do |entry| %>
        <tr>
          <td><%= entry.created_at.to_date %></td>
          <td><%= link_to entry.postReference, journal_entry_path(entry.postReference), method: :get %></td>
          <td><%= entry.description.truncate(60) %></td>
          <% if entry.debit != 0 %>
            <td class="text-right"><%= number_to_currency(entry.debit, precision: 2) %></td>
          <% else %>
            <td></td>
          <% end %>

          <% if entry.credit != 0 %>
            <td class="text-right"><%= number_to_currency(entry.credit, precision: 2) %></td>
          <% else %>
            <td></td>
          <% end %>
          
          <td class="text-right"><%= number_to_currency(entry.balance, precision: 2) %></td>
        </tr>
      <%end%>
    </tbody>
  </table>

<script>
  var minDate, maxDate;
  $.fn.dataTable.ext.search.push(
      function( settings, data, dataIndex ) {
          var min = minDate.val();
          var max = maxDate.val();
          var date = new Date( data[0] );
  
          if (
              ( min === null && max === null ) ||
              ( min === null && date <= max ) ||
              ( min <= date   && max === null ) ||
              ( min <= date   && date <= max )
          ) {
              return true;
          }
          return false;
      }
  );

  $(document).ready(function() {
    minDate = new DateTime($('#mindate'), {
      format: 'MMMM Do YYYY'
    });
    maxDate = new DateTime($('#maxdate'), {
        format: 'MMMM Do YYYY'
    });

    var table = $('#table-layout').DataTable( {
      "pageLength": 100
    });

    $('#mindate, #maxdate').on('change', function () {
      table.draw();
    });

    $(".hBack").on("click", function(e){
      e.preventDefault();
      window.history.back();
    });
  });
</script>